"""Öğretmen modeline branch alanı eklendi

Revision ID: e33fa032e90b
Revises: 4d25e4744b08
Create Date: 2025-03-09 02:00:15.740866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33fa032e90b'
down_revision = '4d25e4744b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
